baseURL = "https://perlweeklychallenge.org/"
languageCode = "en-us"
title = "Perl Weekly Challenge - Perl5 & Perl6"
theme = "timer-hugo"
publishDir = "docs"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "About"
        url     = "/about"
        weight  = 2
    [[menu.nav]]
        name    = "Chart"
        url     = "/chart"
        weight  = 3
    [[menu.nav]]
        name    = "Champions"
        url     = "/champions"
        weight  = 4
    [[menu.nav]]
        name    = "Team"
        url     = "/team"
        weight  = 5
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 6
    [[menu.nav]]
        name    = "FAQ"
        url     = "/faq"
        weight  = 7
    [[menu.nav]]
        name    = "Contact"
        url     = "/contact"
        weight  = 8

# Site Params
[params]
    home = "Home"
    logo = "images/logo.svg"
    dateFormat = "25 March 2019"
    # Meta data
    description = "Perl Weekly Challenge that includes Perl 5 programming and Perl 6 programming."
    author = "Perl Weekly Challenge Team"
    # Google Analitycs
    googleAnalitycsID = "UA-136524905-1"

    # Banner Section
    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Perl Weekly Challenge"
        description = "You learn something valuable from all of the significant events and people, but you never touch your true potential until you challenge yourself to go beyond imposed limitations. - Roy T. Bennett"
        btn     = true
        btnText = "Challenge of the week"
        btnURL  = "/blog/perl-weekly-challenge-022"
        [[params.banner.flipText]]
            title   = "Champion"
        [[params.banner.flipText]]
            title   = "Contributor"
        [[params.banner.flipText]]
            title   = "Mentor"

    # Homepage About Section
    [params.about]
        enable  = true
        title   = "ABOUT ME"
        image   = "images/about/about.jpg"
        github   = "https://github.com/manwar"
        twitter  = "https://twitter.com/cpan_author"
        linkedin = "http://www.linkedin.com/in/mohammadanwar"
        subtitle1 = "JAMSHEDPUR, INDIA (1993 - 1997)"
        content1 = "Let me share my journey of getting into computing. It all started in the year 1993, I just joined the 3 year degree course of B.Sc (Math Honours). It was during the first year, I realised doing just degree is not going to help me secure a job that I needed desparately to support my family. A friend of mine asked me if I am interested to join computer training course. Without giving any thought, I decided to join him and went to a local branch of APTECH, a well known name in computer training institute in India. When we reached their office and enquired about various courses they were offerings. We were told to give an aptitute test before we can join any course. I wasn't prepared for the test but decided to give it a try. We both secured over 90% mark in the test. My friend was fully prepared, so he started dicussing about the courses. At the end he decided to join one year course in \"Diploma In Information and System Management\" (DISM). At the time, the fee was INR 13,000. But I didn't have the money to join the course. I told my mother about it. Like any mother, she decided to sell her wedding jewellery to pay my fees. It was important for me to start earning asap. I was hoping this course would help me land a decent job. I joined the course 6 months later. On the very first day of course, I noticed the same friend is my course faculty. He was a bright student, therefore APTECH offered him the job while he was still doing his course there. We were taught Foxpro and COBOL programming language as a part of the course. At the end of the course, I wasn't satisfied with the knowledge I had. So I decided to learn few other programming languages. The trouble was, I didn't have PC/Laptop to practice and also not enough money to buy computer books. I joined a local library called \"Muslim Library\" as it was FREE and started borrowing books from there. The library was very far from where I lived. I had to take 2 bus journeys to get there. Sometimes, I didn't even have enough money to pay the bus fare. My older sister, who used to give home tution, always helped me. I learnt Pascal by just reading books. Then I learnt \"C\" but this time, I found out one of my friend is running computer training institute. So I went to him and asked if I can use his PC when ever it is available. In return I would teach his students. He kindly accepted my offer. While I was still exploring \"C\" language, I saw an advert about a multinational computer training center opening in Jamshedpur called INFOTECH. I decided to apply for the post of Faculty. But I only got the job of \"Lab Assistant\" for INR 2000 per month. For me that was a lot of money as I could support my family, specially my younger brother who was still in college. There was an added advantage being a Lab Assistant, I could have as much PC time as I like. I learnt Oracle during my time there and got promoted to Faculty after one year."
        subtitle2 = "MUMBAI, INDIA (1997 - 2000)"
        content2 = "In the year 1997, I decided to move to bigger city for better opportunities. One of my collague at INFOTECH was going to Mumbai to try his luck. So I decided to join him, as I didn't know anyone in Mumbai. It was really tough first 3 months. My colleague got a good offer in a very big Technology firm and I was still struggling. In the end, I decided to join APTECH as Faculty. It was a case of surviving. I didn't like the job as I was looking for programming role but I had no other choices. After a year or so, the branch manager of APTECH asked me if I am interested to do small project in Foxpro as a part time. I took the offer without any hesitation. This was my first programming role. We built Windows desktop app for a local Rubber Factory. During this time, a friend of my friend from Jamshedpur asked me if I am interested in Perl programming role. It was a startup, INFOFIN, looking for someone keen to learn the language. I gave the interview and got the job. It was better paid (INR 7000/month) than APTECH (INR 5000/month) and satisfying as well. For the first time, I learnt web programming using good old CGI.pm and DBI.pm. No template, everything was in CGI script. A year and half later, I saw a job advert from multinational company, ORIENT, looking for Perl developers. By now, I knew enough of Perl and decided to give it a try. By the grace of ALLAH, I got the job. I couldn't believe when I was told my salary would be INR 15,000/month. I was little worried though with this salary the expectation would be very high. My first day in the office was very interesting. I saw 20+ programmers with different background sitting and doing nothing all day. We used to get FREE lunch as well. It didn't took me long to figure out what was happening. It was kind of body-shopping. Hire programmers and then send them abroad for contracting, mainly UK and USA. I was asked my choice of place, I randomly picked UK."
        subtitle3 = "LONDON, ENGLAND (2000 - till date)"
        content3 = "I still remember arriving at Heathrow airport on a Sunday evening, 2nd April 2000. My manager from London office came to pick me up. He took me to a Gujarati family in Wembley where already 10 other programmers were staying. I came to UK with 2 years work permit on a take home pay package of GBP 1600 after tax. My first few months were really bad. Communication, that too in English, was never my forte. So where ever I used to go for contracting, I would face lots of issues. After a while, I got 2 weeks contract in the city. On the very first day, I impressed my line manager by solving an issue that they couldn't solve for months. At the end of first day, I was offered extended 6 months contract. I was very happy as she was very understanding. After that I got another contract in Dublin for Vodafone for 2 months. It was great working there, very friendly people. I came back to London in Dec 2000 and took contract for company, Torrington Interactive, based in the city. I was working on \"Tuskerdirect\" project. Within few months, the company went into liquidation. Luckily I was approached by the IT manager of Tuskerdirect and he offered me a permanent place rather than contracting. I didn't like contracting so I took the offer. Guess my pay package was now, GBP 2600 after tax. I worked there for 5 years, the longest at any place that time. After that I joined Spinvox where I met Neil Bowers. I had the pleasure of working with him on SMS sending module. Two years later, during redundancy, I left the job and came back to the city. Currently I am working for NTT Europe for nearly 7 years."

    # Call to Action
    [params.cta]
        enable  = true
        title   = "SO WHAT DO YOU THINK ?"
        content = "If you have any suggestions or ideas then please do share with us."
        btnText = "Contact with me"
        btnURL  = "/contact"

